name: Stickerly
favicon: null
layout_spectrum: 0.7979847874958068
typography_spectrum: 0.44450439722277224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6401472992729396
  lightness: 0.3422015029937029
  saturation: 0.08220290625467896
  rhythmicContrast: 0.11950884689576924
purpose: []
